From hellemon@cs.unimaas.nl Sun Jan 22 15:51:21 2006
Received: from mailhost.cs.man.ac.uk ([130.88.192.14]:59978 "EHLO
	mailhost.cs.man.ac.uk") by sunkay.cs.ualberta.ca with ESMTP
	id S560406AbWAVWvV (ORCPT <rfc822;hayward@cs.ualberta.ca>);
	Sun, 22 Jan 2006 15:51:21 -0700
Received: from rpc25 ([130.88.198.119] helo=localhost.localdomain)
	by mailhost with esmtp (Exim 4.14)
	id 1F0o3J-0004al-Ie
	for hayward@cs.ualberta.ca; Sun, 22 Jan 2006 22:51:17 +0000
To:	hayward@cs.ualberta.ca
From:	CG2006 <hellemon@cs.unimaas.nl>
Subject: CG2006 submission 44
Reply-to: hellemon@cs.unimaas.nl
Message-Id: <E1F0o3J-0004al-Ie@mailhost>
Date:	Sun, 22 Jan 2006 22:51:17 +0000
X-Spam-Score: -1.2 (-)
X-Scanner: exiscan for exim4 (http://duncanthrax.net/exiscan/) *1F0o3J-0004al-Ie*WdtyvzOwGSc*
Return-Path: <hellemon@cs.unimaas.nl>
X-Envelope-To: <hayward@cs.ualberta.ca> (uid 60001)
X-Orcpt: rfc822;hayward@cs.ualberta.ca
Original-Recipient: rfc822;hayward@cs.ualberta.ca
Status: RO
Content-Length: 321
Lines: 14

Dear authors,

We have successfully received your paper:

  Authors : Ryan Hayward, Broderic Arneson and Philip Henderson
  Title   : Verifying Hex Strategies
  Number  : 44
  Paper   : http://www.easychair.org/CG2006/SDdlVhOvo9/44_wwj7L6oNvX.ps

Thank you for submitting to CG2006.

Best regards,

EasyChair for CG2006.

