From ph@cs.ualberta.ca Wed Jun 13 10:00:07 2007

Done!

----- Original Message ----- 
From: "Donkers J (MICC)" <Donkers@MICC.unimaas.nl>
To: "Philip Henderson" <ph@cs.ualberta.ca>; "Bosch T (van den) (MICC)" 
<T.vandenBosch@MICC.unimaas.nl>
Sent: Wednesday, June 13, 2007 1:09 AM
Subject: RE: Turin Proceedings


Dear Philip,

We received the fax in good order, thank you.

Your paper will appear in LNCS volume 4630, most probably on pages
113-123.

Regards,

Jeroen Donkers
